"""initial migration

Revision ID: 725331157869
Revises: a1150ce1efe5
Create Date: 2020-05-10 22:21:27.372435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725331157869'
down_revision = 'a1150ce1efe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
